version: '3.9'

services:

  db_test:
    container_name: db_test
    image: postgres:16
    ports:
         - 5432:5432
    restart: always
    environment:
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=root
    - POSTGRES_DB=test